server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:medical
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        jdbc:
          batch_size: 5
        order_updates: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    com.medical: DEBUG